spring.application.name=ecombackend
spring.data.mongodb.database=ecommerce
spring.data.mongodb.uri=mongodb+srv://best:anand123@cluster0.0ffrhwj.mongodb.net/ecommerce

spring.profiles.active=dev
logging.level.org.springframework.security=DEBUG


jwt.secret=jhdfffhjnvdkkskf
jwt.expiration=36000000
braintree.merchantId = p2bgc7kdzdd2gjbs
braintree.publicKey=2hqtcmjvphyj6t78
braintree.privateKey=965a9dbc85b933b23063ca5160802918
braintree.environment=sandbox
